# Generated by Django 4.1.7 on 2023-04-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stdno', models.IntegerField()),
                ('Stdname', models.CharField(max_length=40)),
                ('Srofpic', models.FileField(blank=True, null=True, upload_to='')),
                ('StdAdd', models.CharField(max_length=40)),
            ],
        ),
    ]
